call C:\Users\owner\anaconda3\Scripts\activate.bat

python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_00.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_01.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_02.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_03.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_04.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_05.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_06.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_07.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_08.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_09.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_10.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_11.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_12.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_13.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_14.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_15.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_16.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_17.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_18.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_19.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_20.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_21.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_22.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_23.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_24.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_25.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_26.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_27.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_28.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_29.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_30.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_31.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_32.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_33.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_34.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_35.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_36.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_37.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_38.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_39.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_40.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_41.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_42.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_43.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_44.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_45.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_46.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_47.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_48.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_49.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_50.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_51.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_52.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_53.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_54.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_55.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_56.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_57.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_58.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_59.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_60.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_61.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_62.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_63.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_64.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_65.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_66.png
python pose_detector.py posenet models/coco_posenet.npz --img outputdir/TuckBack_5_frame_67.png

pause
